---
name: cleaner_tinymce_config
---
SilverStripe\Forms\HTMLEditor\HTMLEditorField:
  default_rows: 5

SilverStripe\Security\Group:
  extensions:
    - Sunnysideup\CleanerTinyMCEConfig\Extensions\HandyHtmlEditorConfig

SilverStripe\Admin\LeftAndMain:
  extensions:
    - Sunnysideup\CleanerTinyMCEConfig\Extensions\HtmlEditorAdminExtension
